include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - flutter/**        # Flutter SDK git submodule — not part of this package
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**

linter:
  rules:
    curly_braces_in_flow_control_structures: false
    avoid_print: false
